services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
      - "8201:8201"
    volumes:
      - ./vault:/etc/vault
      - ./tls:/etc/vault/tls
    cap_add:
      - IPC_LOCK
    command: sh -c "vault server -config=/etc/vault/config.hcl && vault secrets enable -version=1 kv && vault policy write kes-policy /etc/vault/kes-policy.hcl"
    #command: sh -c "vault server -config=/etc/vault/config.hcl"
    #command: sh -c "vault secrets enable -version=1 kv"
    #command: sh -c "vault policy write kes-policy /etc/vault/kes-policy.hcl"
    restart: unless-stopped

  kes:
    image: minio/kes:latest
    container_name: kes
    ports:
      - "7373:7373"
    volumes:
      - ./kes:/etc/kes
      - ./tls:/etc/kes/tls
    command: server --config=/etc/kes/config.yml
    depends_on:
      - vault

volumes:
  vault_data: {}
  vault_audit: {}
