services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    user: root
    network_mode: host
    volumes:
      - ./vault/config:/vault/config:z
      - ./vault/data:/vault/file
      - ./vault/audit:/vault/audit
      - ./vault/cert:/vault/cert:z
    cap_add:
      - IPC_LOCK
    command: server -config=/vault/config/vault.hcl
    restart: unless-stopped

  kes:
    image: minio/kes:latest
    container_name: kes
    ports:
      - "7373:7373"
    volumes:
      - ./kes/config:/etc/kes/config
    command: 
      - server
      - --config=/etc/kes/config/config.yml
    depends_on:
      - vault

volumes:
  vault_data: {}
  vault_audit: {}
