address: 0.0.0.0:7373
admin:
  identity: disabled
tls:
  key: /etc/kes/config/kes.key  
  cert: /etc/kes/config/kes.crt 
policy:
  my-policy:
    allow:
      - /v1/key/create/*
      - /v1/key/generate/*
      - /v1/key/decrypt/*
    identities: []
keystore:
  fs:
    path: "/tmp/kes"  
